template:
  - sensor:
      - name: "DailyCharge"
        unique_id: "7ac7c3b4-1238-4961-9b61-cc2cc8657e7d"
        unit_of_measurement: "kWh"
        device_class: energy
        state_class: total_increasing
        icon: mdi:solar-power
        state: >
          {{ (((as_timestamp(states('sensor.date_time_iso'))) - (as_timestamp(states('input_datetime.dailychargestarttime')))) / 86400 * 0.001) | round(5) }}
